### ISSUE TITLE
Plugin wont load

### ISSUE THREAD

**Issue by GergoEB** [MindustryParty/PluginV2#1]
### I get this error when I try to load the plugin 
I get these errors on startup and the jdbc url is 100% valid (I got it from pterodactyl's database manager)

```[08-04-2021 21:12:13] [E] java.lang.RuntimeException: Error loading mod MindustryPartyPluginV2
        at mindustry.mod.Mods.contextRun(Mods.java:613)
        at mindustry.mod.Mods.lambda$eachClass$26(Mods.java:601)
        at arc.struct.Seq.each(Seq.java:193)
        at mindustry.mod.Mods.eachClass(Mods.java:601)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:84)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:66)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: Malformed database URL, failed to parse the URL authority segment 'u44810_0qgC2VgnmR:+qSn19Jib=JxQV^h@G1UTm@q@<REDACTED>:3306'.
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:581)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at party.mindustry.pluginv2.MPPV2.init(MPPV2.java:87)
        at mindustry.mod.Mods.lambda$eachClass$25(Mods.java:601)
        at mindustry.mod.Mods.contextRun(Mods.java:611)
        ... 6 more
Caused by: java.sql.SQLNonTransientConnectionException: Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: Malformed database URL, failed to parse the URL authority segment 'u44810_0qgC2VgnmR:+qSn19Jib=JxQV^h@G1UTm@q@<REDACTED>:3306'.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:79)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:131)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:221)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
        ... 11 more
Caused by: com.mysql.cj.exceptions.UnableToConnectException: Cannot load connection class because of underlying exception: com.mysql.cj.exceptions.WrongArgumentException: Malformed database URL, failed to parse the URL authority segment 'u44810_0qgC2VgnmR:+qSn19Jib=JxQV^h@G1UTm@q@<REDACTED>:3306'.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
        ... 17 more
Caused by: com.mysql.cj.exceptions.WrongArgumentException: Malformed database URL, failed to parse the URL authority segment 'u44810_0qgC2VgnmR:+qSn19Jib=JxQV^h@G1UTm@q@<REDACTED>:3306'.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.conf.ConnectionUrlParser.parseAuthoritySegment(ConnectionUrlParser.java:278)
        at com.mysql.cj.conf.ConnectionUrlParser.parseAuthoritySection(ConnectionUrlParser.java:183)
        at com.mysql.cj.conf.ConnectionUrlParser.getHosts(ConnectionUrlParser.java:653)
        at com.mysql.cj.conf.ConnectionUrl$Type.getConnectionUrlInstance(ConnectionUrl.java:194)
        at com.mysql.cj.conf.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:280)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:195)
        ... 16 more```

**Comment by OnlyGergo** [comment]
ive tried a different jdbc and it still wont work, different error
```SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[08-05-2021 18:53:14] [E] java.lang.RuntimeException: Error loading mod MindustryPartyPluginV2
        at mindustry.mod.Mods.contextRun(Mods.java:613)
        at mindustry.mod.Mods.lambda$eachClass$26(Mods.java:601)
        at arc.struct.Seq.each(Seq.java:193)
        at mindustry.mod.Mods.eachClass(Mods.java:601)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:84)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:66)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:54)
Caused by: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, jdbc:sqlserver://51.77.202.155:3306;database=players;integratedSecurity=false;user=u44810_0qgC2VgnmR;password=<masked>;instanceName=SQL
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:110)
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:325)
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at party.mindustry.pluginv2.MPPV2.init(MPPV2.java:87)
        at mindustry.mod.Mods.lambda$eachClass$25(Mods.java:601)
        at mindustry.mod.Mods.contextRun(Mods.java:611)
        ... 6 more```

**Comment by OnlyGergo** [comment]
Just had to get rid of any "=" and "@" inside the url (rotated changed password in phpMyAdmin) then i had to change time zone to UTC in url
